kind = "web"
previewPath = "/"
title = "Ishay Infotech Website"
version = "1.0.0"
id = "artifacts/ishay-infotech"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19224

[services.development]
run = "pnpm --filter @workspace/ishay-infotech run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ishay-infotech", "run", "build" ]
publicDir = "artifacts/ishay-infotech/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19224"
BASE_PATH = "/"
